#!/bin/bash

# Get maximized state in case we need it
MAXIMIZED=`xprop -id $(xdotool getwindowfocus) | grep "_NET_WM_STATE(ATOM) = _NET_WM_STATE_MAXIMIZED_HORZ, _NET_WM_STATE_MAXIMIZED_VERT" | wc -l`

# Make sure we are not attempting to close XFCE's Desktop Root Window
WINDOWNAME=`xdotool getwindowfocus getwindowname`

if ! [ $WINDOWNAME == "Desktop" ]
then
	if [ $1 == "close" ]
	then
		wmctrl -c :ACTIVE:
	fi

	if [ $1 == "minimize" ]
	then
		xdotool getwindowfocus windowminimize	
	fi

	if [ $1 == "maxrestore" ]
	then
		if [ $MAXIMIZED -gt 0 ]
		then
			wmctrl -r :ACTIVE: -b remove,maximized_vert,maximized_horz
		else
			wmctrl -r :ACTIVE: -b toggle,maximized_vert,maximized_horz
		fi
	fi
fi
